### ISSUE TITLE
Tracking issue for USB/PCI runtime power management issues

### ISSUE THREAD

**Issue by TheAlexDev23** [TheAlexDev23/power-options#14]
Enabling usb runtime pm by default might disable some usb devices that the user does not want to. Such as input devices. Excluding usb runtime pm settings by default is not an option beacause that's what power-options is meant to be: a program that generates comfortable defaults but also allows the user to change them.

Here are some keypoints:

 - Disabling autosuspend by default on power-saving profiles is against the spirit of the program.

- If I'm not mistaken there are some methods to check if a usb device is an input/audio device, so including those in the blacklist by default could be a solution.

- Making usb autosuspend use a whitelist by default, but that's not much different from disabling autuspend directly.

- Technically, the profiles do not get generated during install, but when the daemon starts for the first time, which so happens to be after a program is installed. Requiring the user to manually enable the daemon and then receive an interactive screen on which options they might want to disable seems like a plausible option.

- Also, I could make power-options behave like TLP on install, just a single empty profile. And when a certain frontend is opened for the first time then provide a dialogue for optional profile generation with whatever warnings are required. 

Still debating on which option to use. Alternative suggestions and your opinions are welcomed in this thread.

**Comment by DistantThunder** [comment]
Hello, 

My take is that before running *ANY* modification, a warning/agreement screen should pop on the user screen to warn them with a link to the exhaustive list of of default changes the program performs during installation.

**Comment by TheAlexDev23** [comment]
There's a big warning in the first line of the wiki, given that it's the first place the users visit I feel like it isn't a bad place. The program generates 5 different profiles with over 100 modified settings EACH. Dumping a wall of text with all the settings that the profiles change might make users treat it like the privacy policy: too long to read so they just accept it. Maybe a reduced amount of information with the potential issues that might arise?

**Comment by DistantThunder** [comment]
> given that it's the first place the users visit

I'd say that's a generous statement on behalf of the users. For better visibility, I'd still prioritize a warning with a disclaimer and a link to the wiki rather than indeed dumping the potentially modified settings. 

I also want to underline that modifying 100+ settings (because at least 1 profile is applied by default if I understand correctly?) on first launch without any clear visible clue and relying on the user having *potentially* read the wiki doesn't sound ideal?

**Comment by DistantThunder** [comment]
* So forcing the user to start the daemon manually, with a warning that profiles will be generated and applied and a link to more details is what you're suggesting?

Not forcing anything, whatever is the sequence of activation of the program, before the default profile launches, a GUI prompt should warn the user and make double sure that they're about to apply a number of settings that *should* be ideal but could have some unwanted effect depending on their hardware compatibility ('cause that's the one variable you can't control).

>  Ultimately, the goal for power-options is to provide the most pleasant defaults so that users without technical knowledge could install this program without any tinkering.

Of course. It's just a matter of raising awareness.

> Which implies setting modification in the background.

Just one initial warning screen with the possibility to back off, in case the users didn't read the Wiki (which I will believe is a sizeable amount of them) and then we're good. That screen may content a quick text about the settings about to be applied possibly not being optimal and you claiming no responsibility etc..

**Comment by TheAlexDev23** [comment]
Dynamic dialogs during installation are a bit tricky as they differ from package manager to package manager, and some might not support them. What I was previously suggesting is to not start the systemd daemon during install, but ask the user to run some sort of command, e.g `power-daemon-mgr setup`, which will provide a cli or a yad dialog with the warning and a link to the wiki.

And to solve the usb auto-suspend problem, provide a warning message that informs of the potential dangers and allows the user to disable runtime pm during install so that it can be re enabled later manually with the proper blacklisting in place.

Seems like a great option.

**Comment by TheAlexDev23** [comment]
Or maybe actually make usb auto-suspend options whitelisted in the default profiles, but show the user a popup when using one of the frontends for the first time that it’s recommended to change them into a blacklist.

The dilemma is that usb auto-suspend is common enough in power saving that enabling it by default should be reasonable, but on the other hand it could cause some issues. I wonder how alternatives handle it, something like Windows. They probably have some sort of runtime pm equivalent for usb devices on lower energy profiles. But I don’t recall having any similar issues, do you or somebody else know what’s the common way to handle these settings?

**Comment by DistantThunder** [comment]
The USB Auto-suspend is just a symptom, it could be that or any of the other 100+ settings, we don't need to find or focus on one in particular from my PoV.

As for the implementation, the daemon itself could run the pop up, since it's only when it starts the profile applying takes place.

Or the systemd service could run some separate pre-run script that would check the existence of a "/var/lib/power-manager/user_agreement.lock" file. If it exists, it runs the daemon unimpeded. If not, it stops with a warning visible in "systemctl status power-mgr" or equivalent?

**Comment by TheAlexDev23** [comment]
Yeah I agree with the user consent popup, that is a must-have that I will add as soon as I can. 

But despite the user agreement, the defaults also need to work. The first priority is of course to make sure no potential damage could be caused by the default settings (I followed the advice of all the power saving guides on that and double checked everything), if there are any then they need to be fixed ASAP. USB runtime pm *shouldn't* cause any serious damages (such as data loss), because, as far as I'm aware USB devices do not get denied power, they just enter U1-U3 power states depending on how the kernel devs decided to implement that. The second priority then is to get rid of said non-destructive inconveniences, just showing a consent form and then blaming the user when their keyboard goes off every 10 seconds isn't quite nice imo. That's why I was asking for solutions to the USB and PCI runtime pm defaults specifically on top of the acknowledgement popup.

**Comment by TheAlexDev23** [comment]
I've also added a [wiki page](https://github.com/TheAlexDev23/power-options/wiki/Default-generated-settings) explaining the defaults which the popup links to.

**Comment by TheAlexDev23** [comment]
I will be closing this issue because the goal of informing the user has been achieved. And USB autosuspend options will remain the way they currently are until further complaints are received.

**Comment by DistantThunder** [comment]
Thank you for doing this work. I believe the USB autosuspend was just illustrative of how one such settings could be problematic rather than being focused by itself and could have just been left alone but ok.

Also, don't forget a fallback for CLI only users: if you don't detect a graphical session, just proceed with a huge warning in the logs.

**Comment by TheAlexDev23** [comment]
> if you don't detect a graphical session, just proceed with a huge warning in the logs.

Are you aware of any apis that I can use to do that? I'm assuming that if a graphical session is missing yad will exit with a non-zero exit code which will be interpreted the same way as pressing the cancel button and will end up generating a single default profile.
