### ISSUE TITLE
Add a bubble icon near titles for tooltips on hover in webview frontend

### ISSUE THREAD

**Issue by TheAlexDev23** [TheAlexDev23/power-options#17]
Currently you need to hover over the input field to get a tooltip explaining what the setting does or why is it disabled. A bubble icon that makes the tooltip appear on hover, will likely be more helpful.

**Comment by TisFoolish** [comment]
Having it small and in the upper right corner would help draw the eye towards it as it would be right next to whatever toggle is used for that section without being obtrusive
