### ISSUE TITLE
Panic Popup Dialogue When Running GTK Frontend 

### ISSUE THREAD

**Issue by fdf999** [TheAlexDev23/power-options#19]
_Continuation from Reddit_ 
I installed all the dependencies(hopefully), and when I run power-options using the GTK frontend, a popup appears, showing me this: 
![Screenshot from 2024-09-18 09-24-50](https://github.com/user-attachments/assets/c04cdd72-4d77-479b-b673-877d0ba210bd)

I did reboot my system like it suggested yet that did not resolve the problem. I would check that the power-options daemon is running but I don't know how to check that. 
If you need any more information I would happy to provide that. Thanks for you help.

**Comment by TheAlexDev23** [comment]
What's the output for `systemctl status power-options`?

**Comment by fdf999** [comment]
`× power-options.service - power-options daemon
     Loaded: loaded (/usr/lib/systemd/system/power-options.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-09-18 09:22:24 MDT; 27min ago
   Duration: 34ms
    Process: 3181 ExecStart=/usr/bin/power-daemon-mgr daemon (code=exited, status=101)
   Main PID: 3181 (code=exited, status=101)
        CPU: 45ms

Sep 18 09:22:24 gs-ltp power-daemon-mgr[3181]: Could not run command: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Sep 18 09:22:24 gs-ltp power-daemon-mgr[3181]: thread '<unnamed>' panicked at crates/power-daemon/src/helpers.rsINFO ==> [power_daemon::profile]: Applying Network settings on Th>
Sep 18 09:22:24 gs-ltp power-daemon-mgr[3181]: :10:
Sep 18 09:22:24 gs-ltp power-daemon-mgr[3181]: Could not run command: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Sep 18 09:22:24 gs-ltp power-daemon-mgr[3181]: thread '<unnamed>' panicked at crates/power-daemon/src/helpers.rs:80:10:
Sep 18 09:22:24 gs-ltp power-daemon-mgr[3181]: Could not run command: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Sep 18 09:22:24 gs-ltp power-daemon-mgr[3181]: thread '<unnamed>' panicked at crates/power-daemon/src/helpers.rs:132:10:
Sep 18 09:22:24 gs-ltp power-daemon-mgr[3181]: Could not run command: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Sep 18 09:22:24 gs-ltp systemd[1]: power-options.service: Main process exited, code=exited, status=101/n/a
Sep 18 09:22:24 gs-ltp systemd[1]: power-options.service: Failed with result 'exit-code'.
`

**Comment by TheAlexDev23** [comment]
Is zsh installed in your system? Please verify that *all* the mandatory dependencies are installed from this [list](https://github.com/TheAlexDev23/power-options?tab=readme-ov-file#dependencies)

**Comment by fdf999** [comment]
hey, sorry for taking a while to respond. But yes, I was missing some dependencies which I thought I already had, so now it is working as intended. I apologize for annoying you about this, you can close this issue now.

**Comment by TheAlexDev23** [comment]
That's ok, you didn't annoy anyone. That's what issues are for!
