### ISSUE TITLE
GTK no settings

### ISSUE THREAD

**Issue by Mahmoudbat** [TheAlexDev23/power-options#29]
no options appear when i open power-options-gtk

```
$ power-options-gtk 

(power-options-gtk:32245): Gtk-WARNING **: 21:03:07.640: gtk_window_set_titlebar() called on a realized window

``` 
here is a screenshot

![image](https://github.com/user-attachments/assets/89cd2454-1b20-4f95-a2cb-b4c485fd1caa)

**Comment by TheAlexDev23** [comment]
The left navigation bar is extended to the end of the screen. Try to drag the mouse at the rightmost part of the window and resize it to its normal size.

**Comment by Mahmoudbat** [comment]
it worked thank you
