### ISSUE TITLE
Could not spawn popup

### ISSUE THREAD

**Issue by toumorokoshi** [TheAlexDev23/power-options#30]
**Describe the bug**

When I run `power-options-gtk` on my Ubuntu laptop (HP Spectre X360) - I get the following:

```
tsutsumi@yusuke-hp:~$ sudo RUST_BACKTRACE=1 power-options-gtk 
thread 'main' panicked at crates/frontend-gtk/src/main.rs:84:20:
Could not spawn popup: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/result.rs:1653:5
   3: frontend_gtk::main
```

**To Reproduce**

- install [power options via the process explained in other-distros](https://github.com/TheAlexDev23/power-options?tab=readme-ov-file#other-distros--from-source).

**System Info:**
 - OS: Ubuntu 24.04 

```
tsutsumi@yusuke-hp:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"
```

 - Kernel Version: `Linux yusuke-hp 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
 - power-options version 

Clone from head: ```
tsutsumi@yusuke-hp:~$ sudo RUST_BACKTRACE=1 power-daemon-mgr --version
power-daemon-mgr 1.0.0
```

 - The output of `power-options-mgr print-system-info` (attached)
[out.txt](https://github.com/user-attachments/files/17455331/out.txt)

 - The full/recent logs of the `power-options.service` systemd daemon.
```
Oct 20 21:37:42 yusuke-hp systemd[1]: Started power-options.service - power-options daemon.
Oct 20 21:37:42 yusuke-hp power-daemon-mgr[2471]: thread 'main' panicked at crates/power-daemon/src/lib.rs:371:44:
Oct 20 21:37:42 yusuke-hp power-daemon-mgr[2471]: Could not read config: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Oct 20 21:37:42 yusuke-hp power-daemon-mgr[2471]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Oct 20 21:37:42 yusuke-hp systemd[1]: power-options.service: Main process exited, code=exited, status=101/n/a
Oct 20 21:37:42 yusuke-hp systemd[1]: power-options.service: Failed with result 'exit-code'.
Oct 20 22:19:43 yusuke-hp systemd[1]: Started power-options.service - power-options daemon.
Oct 20 22:19:43 yusuke-hp power-daemon-mgr[5170]: thread 'main' panicked at crates/power-daemon/src/lib.rs:371:44:
Oct 20 22:19:43 yusuke-hp power-daemon-mgr[5170]: Could not read config: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Oct 20 22:19:43 yusuke-hp power-daemon-mgr[5170]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Oct 20 22:19:43 yusuke-hp systemd[1]: power-options.service: Main process exited, code=exited, status=101/n/a
Oct 20 22:19:43 yusuke-hp systemd[1]: power-options.service: Failed with result 'exit-code'.
```

**Additional context**
Add any other context about the problem here.

**Comment by TheAlexDev23** [comment]
Check if you `yad` installed in your system as it is a required dependency for popups. Note that the daemon also fails because it can't find any configuration files, I'm assuming this is because the setup process couldn't finish, also likely due to the `yad` dependency missing. If installing yad fixes the gtk frontend panic, rerun `sudo power-daemon-mgr setup` to complete the failed setup process.
